// Not yet Autogenerated file. DO NOT EDIT!

pub const c = @cImport({
    @cDefine("GUI_SHOWCASE_IMPLEMENTATION", {});
    @cInclude("./showcase/mod.h");

    @cDefine("GUI_SETTINGS_IMPLEMENTATION", {});
    @cInclude("./settings/mod.h");
});

pub const modules = .{
    @import("showcase/mod.zig"),
    @import("settings/mod.zig"),
};

pub const names = .{
    "showcase",
    "settings",
};

pub const SettingsState = c.GuiSettingsState;
pub const ShowcaseState = c.GuiShowcaseState;
