steps:
  build:
    image: debian:stable-slim
    when:
      event: [tag, push]
    commands:
      - echo building
      # - apt -y update
      # - apt -y upgrade
      - touch test
      # Install zigup
      # - apt-get update -y && apt-get install -y wget xz-utils
      # - wget -O zig.tar.xz https://ziglang.org/download/0.12.1/zig-linux-x86_64-0.12.1.tar.xz 
      # - tar -xf zig.tar.xz
      # - ./zig-linux-x86_64-0.12.1/zig version
      # # - wget -O - https://github.com/marler8997/zigup/releases/download/v2024_05_05/zigup-x86_64-linux.tar.gz | tar xz
      # # - ./zigup 0.12.0
      # # - ./zig version
      # - apt install -y build-essential git
      # - apt install -y libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev
      # - ./zig-linux-x86_64-0.12.1/zig build
      # - ls zig-out/bin
      # - echo "Done!"

  publish:
    image: woodpeckerci/plugin-release
    when:
      event: [tag, push]
    settings:
      files:
        # Could also be "hello-world*" to match both
        # - 'zig-out/Z-body'
        - 'test'
      api_key:
        from_secret: ACCESS_TOKEN
      

    
